--------------------------------------------------------
--  Fichier créé - lundi-décembre-06-2021   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table ANIMAUX
--------------------------------------------------------

  CREATE TABLE "SARRA"."ANIMAUX" 
   (	"ID_ANIMAL" NUMBER(38,0), 
	"TYPE" VARCHAR2(20 BYTE), 
	"NUMERO_CAGE" NUMBER(38,0), 
	"AGE" NUMBER(38,0), 
	"RECLAMATION" VARCHAR2(20 BYTE), 
	"NOURITURE" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table COMPTES
--------------------------------------------------------

  CREATE TABLE "SARRA"."COMPTES" 
   (	"IDENTIFIANT" VARCHAR2(20 BYTE), 
	"MDP" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table EMPLOYE
--------------------------------------------------------

  CREATE TABLE "SARRA"."EMPLOYE" 
   (	"IDENTIFIANTE" VARCHAR2(20 BYTE), 
	"NOM" VARCHAR2(20 BYTE), 
	"PRENOM" VARCHAR2(20 BYTE), 
	"SALAIRE" FLOAT(126), 
	"IDSUPERVISEUR" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table FOURNIR
--------------------------------------------------------

  CREATE TABLE "SARRA"."FOURNIR" 
   (	"ID_PRODUIT_PK1" NUMBER, 
	"ID_ANIMAL_PK2" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table MAGASINS
--------------------------------------------------------

  CREATE TABLE "SARRA"."MAGASINS" 
   (	"ID_MAGASIN" VARCHAR2(20 BYTE), 
	"PRIX_LOCATION" FLOAT(126), 
	"ETAT" NUMBER, 
	"ID_LOCATAIRE" VARCHAR2(20 BYTE), 
	"LIBELLE" VARCHAR2(20 BYTE), 
	"ID_EMPLOYES_FK1" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table NOURITURE
--------------------------------------------------------

  CREATE TABLE "SARRA"."NOURITURE" 
   (	"ID_MEAL" NUMBER, 
	"TEMPS" TIMESTAMP (6) DEFAULT CURRENT_TIMESTAMP, 
	"ANIMAL" NUMBER(38,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table PRENDRE_EN_CHARGE
--------------------------------------------------------

  CREATE TABLE "SARRA"."PRENDRE_EN_CHARGE" 
   (	"ID_ANIMAL_PK1" NUMBER, 
	"ID_EMPLOYE_PK2" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table PRODUITS
--------------------------------------------------------

  CREATE TABLE "SARRA"."PRODUITS" 
   (	"ID_PRODUIT" NUMBER, 
	"NOM_PRODUIT" VARCHAR2(20 BYTE), 
	"LIBELLE_PRODUIT" VARCHAR2(20 BYTE), 
	"NBRE_EXEMPLAIRE" NUMBER, 
	"ID_FOURNISSEUR" NUMBER, 
	"PRIX" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table VISITES
--------------------------------------------------------

  CREATE TABLE "SARRA"."VISITES" 
   (	"IDENTIFIANTTICKET" VARCHAR2(20 BYTE), 
	"PRIXTICKET" NUMBER, 
	"IDENTIFIANTVISITEUR" VARCHAR2(20 BYTE), 
	"NOMBREVISITES" NUMBER, 
	"DATEVISITE" VARCHAR2(30 BYTE), 
	"ABONNEMENT" VARCHAR2(20 BYTE), 
	"ID_ANIMAL_FK1" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
REM INSERTING into SARRA.ANIMAUX
SET DEFINE OFF;
Insert into SARRA.ANIMAUX (ID_ANIMAL,TYPE,NUMERO_CAGE,AGE,RECLAMATION,NOURITURE) values ('0','tigre','6','8',null,'viande');
Insert into SARRA.ANIMAUX (ID_ANIMAL,TYPE,NUMERO_CAGE,AGE,RECLAMATION,NOURITURE) values ('1','lion','5','6',null,'Carnivore');
REM INSERTING into SARRA.COMPTES
SET DEFINE OFF;
Insert into SARRA.COMPTES (IDENTIFIANT,MDP) values ('admin','admin');
Insert into SARRA.COMPTES (IDENTIFIANT,MDP) values ('sarra','sarra');
Insert into SARRA.COMPTES (IDENTIFIANT,MDP) values ('yasmine','yasmine');
Insert into SARRA.COMPTES (IDENTIFIANT,MDP) values ('omar','omar');
REM INSERTING into SARRA.EMPLOYE
SET DEFINE OFF;
Insert into SARRA.EMPLOYE (IDENTIFIANTE,NOM,PRENOM,SALAIRE,IDSUPERVISEUR) values ('211.33.134.25','elkar','omar1','6000',null);
Insert into SARRA.EMPLOYE (IDENTIFIANTE,NOM,PRENOM,SALAIRE,IDSUPERVISEUR) values ('92.129.16.57','elkar','omar2',null,null);
REM INSERTING into SARRA.FOURNIR
SET DEFINE OFF;
REM INSERTING into SARRA.MAGASINS
SET DEFINE OFF;
REM INSERTING into SARRA.NOURITURE
SET DEFINE OFF;
Insert into SARRA.NOURITURE (ID_MEAL,TEMPS,ANIMAL) values ('1',to_timestamp('06/12/21 19:49:23,016000000','DD/MM/RR HH24:MI:SSXFF'),'0');
REM INSERTING into SARRA.PRENDRE_EN_CHARGE
SET DEFINE OFF;
REM INSERTING into SARRA.PRODUITS
SET DEFINE OFF;
Insert into SARRA.PRODUITS (ID_PRODUIT,NOM_PRODUIT,LIBELLE_PRODUIT,NBRE_EXEMPLAIRE,ID_FOURNISSEUR,PRIX) values ('54','omo','Alimentaires','5','5','4');
Insert into SARRA.PRODUITS (ID_PRODUIT,NOM_PRODUIT,LIBELLE_PRODUIT,NBRE_EXEMPLAIRE,ID_FOURNISSEUR,PRIX) values ('52','pril','Alimentaires','2','1158','12');
Insert into SARRA.PRODUITS (ID_PRODUIT,NOM_PRODUIT,LIBELLE_PRODUIT,NBRE_EXEMPLAIRE,ID_FOURNISSEUR,PRIX) values ('70','gants','Alimentaires','3','148','15');
Insert into SARRA.PRODUITS (ID_PRODUIT,NOM_PRODUIT,LIBELLE_PRODUIT,NBRE_EXEMPLAIRE,ID_FOURNISSEUR,PRIX) values ('55','lglg','Alimentaires','5','63','2');
Insert into SARRA.PRODUITS (ID_PRODUIT,NOM_PRODUIT,LIBELLE_PRODUIT,NBRE_EXEMPLAIRE,ID_FOURNISSEUR,PRIX) values ('554','jkfll','Alimentaires','61','88','5');
Insert into SARRA.PRODUITS (ID_PRODUIT,NOM_PRODUIT,LIBELLE_PRODUIT,NBRE_EXEMPLAIRE,ID_FOURNISSEUR,PRIX) values ('125','viande','Alimentaires','15','56565','100');
REM INSERTING into SARRA.VISITES
SET DEFINE OFF;
Insert into SARRA.VISITES (IDENTIFIANTTICKET,PRIXTICKET,IDENTIFIANTVISITEUR,NOMBREVISITES,DATEVISITE,ABONNEMENT,ID_ANIMAL_FK1) values ('jdfik','86','555','0','jeu. d??c. 2 2021','Oui',null);
Insert into SARRA.VISITES (IDENTIFIANTTICKET,PRIXTICKET,IDENTIFIANTVISITEUR,NOMBREVISITES,DATEVISITE,ABONNEMENT,ID_ANIMAL_FK1) values ('sarra','7','52','0','ven. nov. 12 2021','Oui',null);
Insert into SARRA.VISITES (IDENTIFIANTTICKET,PRIXTICKET,IDENTIFIANTVISITEUR,NOMBREVISITES,DATEVISITE,ABONNEMENT,ID_ANIMAL_FK1) values ('klp','2','1','0','dim. nov. 14 2021','Oui',null);
Insert into SARRA.VISITES (IDENTIFIANTTICKET,PRIXTICKET,IDENTIFIANTVISITEUR,NOMBREVISITES,DATEVISITE,ABONNEMENT,ID_ANIMAL_FK1) values ('testh','20','17','0','mar. nov. 9 2021','Oui',null);
Insert into SARRA.VISITES (IDENTIFIANTTICKET,PRIXTICKET,IDENTIFIANTVISITEUR,NOMBREVISITES,DATEVISITE,ABONNEMENT,ID_ANIMAL_FK1) values ('mlo','2','125','0','dim. nov. 14 2021','Oui',null);
Insert into SARRA.VISITES (IDENTIFIANTTICKET,PRIXTICKET,IDENTIFIANTVISITEUR,NOMBREVISITES,DATEVISITE,ABONNEMENT,ID_ANIMAL_FK1) values ('test','20','5','0','lun. nov. 15 2021','Oui',null);
Insert into SARRA.VISITES (IDENTIFIANTTICKET,PRIXTICKET,IDENTIFIANTVISITEUR,NOMBREVISITES,DATEVISITE,ABONNEMENT,ID_ANIMAL_FK1) values ('ttest','7','2','0','mar. nov. 16 2021','Oui',null);
Insert into SARRA.VISITES (IDENTIFIANTTICKET,PRIXTICKET,IDENTIFIANTVISITEUR,NOMBREVISITES,DATEVISITE,ABONNEMENT,ID_ANIMAL_FK1) values ('abbc','8','12','2','lun. nov. 8 2021','Oui',null);
Insert into SARRA.VISITES (IDENTIFIANTTICKET,PRIXTICKET,IDENTIFIANTVISITEUR,NOMBREVISITES,DATEVISITE,ABONNEMENT,ID_ANIMAL_FK1) values ('sml','25','148','0','mar. nov. 9 2021','Non',null);
Insert into SARRA.VISITES (IDENTIFIANTTICKET,PRIXTICKET,IDENTIFIANTVISITEUR,NOMBREVISITES,DATEVISITE,ABONNEMENT,ID_ANIMAL_FK1) values ('smll','25','148','0','mar. nov. 9 2021','Non',null);
Insert into SARRA.VISITES (IDENTIFIANTTICKET,PRIXTICKET,IDENTIFIANTVISITEUR,NOMBREVISITES,DATEVISITE,ABONNEMENT,ID_ANIMAL_FK1) values ('ll','8','7','0','lun. nov. 8 2021','Oui',null);
Insert into SARRA.VISITES (IDENTIFIANTTICKET,PRIXTICKET,IDENTIFIANTVISITEUR,NOMBREVISITES,DATEVISITE,ABONNEMENT,ID_ANIMAL_FK1) values ('kjj','3','76','0','mar. nov. 30 2021','Oui',null);
Insert into SARRA.VISITES (IDENTIFIANTTICKET,PRIXTICKET,IDENTIFIANTVISITEUR,NOMBREVISITES,DATEVISITE,ABONNEMENT,ID_ANIMAL_FK1) values ('kl','5','4','0','lun. nov. 8 2021','Oui',null);
Insert into SARRA.VISITES (IDENTIFIANTTICKET,PRIXTICKET,IDENTIFIANTVISITEUR,NOMBREVISITES,DATEVISITE,ABONNEMENT,ID_ANIMAL_FK1) values ('ok','8','3','0','lun. nov. 8 2021','Oui',null);
Insert into SARRA.VISITES (IDENTIFIANTTICKET,PRIXTICKET,IDENTIFIANTVISITEUR,NOMBREVISITES,DATEVISITE,ABONNEMENT,ID_ANIMAL_FK1) values ('m','7','5','0','lun. nov. 8 2021','Oui',null);
Insert into SARRA.VISITES (IDENTIFIANTTICKET,PRIXTICKET,IDENTIFIANTVISITEUR,NOMBREVISITES,DATEVISITE,ABONNEMENT,ID_ANIMAL_FK1) values ('kh','65','2','0','lun. nov. 8 2021','Oui',null);
Insert into SARRA.VISITES (IDENTIFIANTTICKET,PRIXTICKET,IDENTIFIANTVISITEUR,NOMBREVISITES,DATEVISITE,ABONNEMENT,ID_ANIMAL_FK1) values ('smllk','14','67','4','mar. nov. 9 2021','Non',null);
Insert into SARRA.VISITES (IDENTIFIANTTICKET,PRIXTICKET,IDENTIFIANTVISITEUR,NOMBREVISITES,DATEVISITE,ABONNEMENT,ID_ANIMAL_FK1) values ('kdj','2','123','0','mar. nov. 9 2021','Oui',null);
Insert into SARRA.VISITES (IDENTIFIANTTICKET,PRIXTICKET,IDENTIFIANTVISITEUR,NOMBREVISITES,DATEVISITE,ABONNEMENT,ID_ANIMAL_FK1) values ('mm','8','45','0','mar. nov. 9 2021','Oui',null);
Insert into SARRA.VISITES (IDENTIFIANTTICKET,PRIXTICKET,IDENTIFIANTVISITEUR,NOMBREVISITES,DATEVISITE,ABONNEMENT,ID_ANIMAL_FK1) values ('mol','14','36','0','mar. nov. 9 2021','Oui',null);
Insert into SARRA.VISITES (IDENTIFIANTTICKET,PRIXTICKET,IDENTIFIANTVISITEUR,NOMBREVISITES,DATEVISITE,ABONNEMENT,ID_ANIMAL_FK1) values ('tttest','7','2','0','mar. nov. 16 2021','Oui',null);
Insert into SARRA.VISITES (IDENTIFIANTTICKET,PRIXTICKET,IDENTIFIANTVISITEUR,NOMBREVISITES,DATEVISITE,ABONNEMENT,ID_ANIMAL_FK1) values ('dora','11','869','3','mar. nov. 16 2021','Oui',null);
Insert into SARRA.VISITES (IDENTIFIANTTICKET,PRIXTICKET,IDENTIFIANTVISITEUR,NOMBREVISITES,DATEVISITE,ABONNEMENT,ID_ANIMAL_FK1) values ('papa','5','53','0','mar. nov. 23 2021','Oui',null);
Insert into SARRA.VISITES (IDENTIFIANTTICKET,PRIXTICKET,IDENTIFIANTVISITEUR,NOMBREVISITES,DATEVISITE,ABONNEMENT,ID_ANIMAL_FK1) values ('plo','4','15','2','mer. d??c. 1 2021','Oui',null);
Insert into SARRA.VISITES (IDENTIFIANTTICKET,PRIXTICKET,IDENTIFIANTVISITEUR,NOMBREVISITES,DATEVISITE,ABONNEMENT,ID_ANIMAL_FK1) values ('mpl','8','23','9','mer. d??c. 1 2021','Non',null);
Insert into SARRA.VISITES (IDENTIFIANTTICKET,PRIXTICKET,IDENTIFIANTVISITEUR,NOMBREVISITES,DATEVISITE,ABONNEMENT,ID_ANIMAL_FK1) values ('amin','1','3','0','mer. d??c. 1 2021','Oui',null);
Insert into SARRA.VISITES (IDENTIFIANTTICKET,PRIXTICKET,IDENTIFIANTVISITEUR,NOMBREVISITES,DATEVISITE,ABONNEMENT,ID_ANIMAL_FK1) values ('pdml','1','158','0','jeu. d??c. 2 2021','Oui',null);
Insert into SARRA.VISITES (IDENTIFIANTTICKET,PRIXTICKET,IDENTIFIANTVISITEUR,NOMBREVISITES,DATEVISITE,ABONNEMENT,ID_ANIMAL_FK1) values ('teste','2','5','0','jeu. d??c. 2 2021','Oui',null);
Insert into SARRA.VISITES (IDENTIFIANTTICKET,PRIXTICKET,IDENTIFIANTVISITEUR,NOMBREVISITES,DATEVISITE,ABONNEMENT,ID_ANIMAL_FK1) values ('jdfi','85','85','0','jeu. d??c. 2 2021','Oui',null);
Insert into SARRA.VISITES (IDENTIFIANTTICKET,PRIXTICKET,IDENTIFIANTVISITEUR,NOMBREVISITES,DATEVISITE,ABONNEMENT,ID_ANIMAL_FK1) values ('testinte','3','158','0','jeu. d??c. 2 2021','Oui',null);
Insert into SARRA.VISITES (IDENTIFIANTTICKET,PRIXTICKET,IDENTIFIANTVISITEUR,NOMBREVISITES,DATEVISITE,ABONNEMENT,ID_ANIMAL_FK1) values ('sarraaa','13','170','3','ven. d??c. 3 2021','Non',null);
--------------------------------------------------------
--  DDL for Index ANIMAUX_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "SARRA"."ANIMAUX_PK" ON "SARRA"."ANIMAUX" ("ID_ANIMAL") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index COMPTES_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "SARRA"."COMPTES_PK" ON "SARRA"."COMPTES" ("IDENTIFIANT") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index EMPLOYES_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "SARRA"."EMPLOYES_PK" ON "SARRA"."EMPLOYE" ("IDENTIFIANTE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index FOURNIR_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "SARRA"."FOURNIR_PK" ON "SARRA"."FOURNIR" ("ID_PRODUIT_PK1", "ID_ANIMAL_PK2") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index MAGASINS_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "SARRA"."MAGASINS_PK" ON "SARRA"."MAGASINS" ("ID_MAGASIN") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index NOURITURE_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "SARRA"."NOURITURE_PK" ON "SARRA"."NOURITURE" ("ID_MEAL") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index PRENDRE_EN_CHARGE_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "SARRA"."PRENDRE_EN_CHARGE_PK" ON "SARRA"."PRENDRE_EN_CHARGE" ("ID_ANIMAL_PK1", "ID_EMPLOYE_PK2") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index PRODUITS_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "SARRA"."PRODUITS_PK" ON "SARRA"."PRODUITS" ("ID_PRODUIT") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index VISITES_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "SARRA"."VISITES_PK" ON "SARRA"."VISITES" ("IDENTIFIANTTICKET") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Trigger ANIMAUX_TRG
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "SARRA"."ANIMAUX_TRG" 
BEFORE INSERT ON ANIMAUX 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    IF INSERTING AND :NEW.ID_ANIMAL IS NULL THEN
      SELECT ANIMAUX_SEQ.NEXTVAL INTO :NEW.ID_ANIMAL FROM SYS.DUAL;
    END IF;
  END COLUMN_SEQUENCES;
END;
/
ALTER TRIGGER "SARRA"."ANIMAUX_TRG" ENABLE;
--------------------------------------------------------
--  DDL for Trigger NOURITURE_TRG1
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "SARRA"."NOURITURE_TRG1" 
BEFORE INSERT ON NOURITURE 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    IF INSERTING AND :NEW.ID_MEAL IS NULL THEN
      SELECT NOURITURE_SEQ1.NEXTVAL INTO :NEW.ID_MEAL FROM SYS.DUAL;
    END IF;
  END COLUMN_SEQUENCES;
END;
/
ALTER TRIGGER "SARRA"."NOURITURE_TRG1" ENABLE;
--------------------------------------------------------
--  DDL for Trigger NOURITURE_TRG
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "SARRA"."NOURITURE_TRG" 
BEFORE INSERT ON NOURITURE 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    NULL;
  END COLUMN_SEQUENCES;
END;
/
ALTER TRIGGER "SARRA"."NOURITURE_TRG" ENABLE;
--------------------------------------------------------
--  Constraints for Table ANIMAUX
--------------------------------------------------------

  ALTER TABLE "SARRA"."ANIMAUX" MODIFY ("TYPE" NOT NULL ENABLE);
  ALTER TABLE "SARRA"."ANIMAUX" ADD CONSTRAINT "ANIMAUX_PK" PRIMARY KEY ("ID_ANIMAL")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "SARRA"."ANIMAUX" MODIFY ("ID_ANIMAL" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table COMPTES
--------------------------------------------------------

  ALTER TABLE "SARRA"."COMPTES" ADD CONSTRAINT "COMPTES_PK" PRIMARY KEY ("IDENTIFIANT")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "SARRA"."COMPTES" MODIFY ("IDENTIFIANT" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table EMPLOYE
--------------------------------------------------------

  ALTER TABLE "SARRA"."EMPLOYE" ADD CONSTRAINT "EMPLOYES_PK" PRIMARY KEY ("IDENTIFIANTE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "SARRA"."EMPLOYE" MODIFY ("IDENTIFIANTE" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table FOURNIR
--------------------------------------------------------

  ALTER TABLE "SARRA"."FOURNIR" ADD CONSTRAINT "FOURNIR_PK" PRIMARY KEY ("ID_PRODUIT_PK1", "ID_ANIMAL_PK2")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "SARRA"."FOURNIR" MODIFY ("ID_ANIMAL_PK2" NOT NULL ENABLE);
  ALTER TABLE "SARRA"."FOURNIR" MODIFY ("ID_PRODUIT_PK1" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table MAGASINS
--------------------------------------------------------

  ALTER TABLE "SARRA"."MAGASINS" ADD CONSTRAINT "MAGASINS_PK" PRIMARY KEY ("ID_MAGASIN")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "SARRA"."MAGASINS" MODIFY ("ID_MAGASIN" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table NOURITURE
--------------------------------------------------------

  ALTER TABLE "SARRA"."NOURITURE" ADD CONSTRAINT "NOURITURE_PK" PRIMARY KEY ("ID_MEAL")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "SARRA"."NOURITURE" MODIFY ("ANIMAL" NOT NULL ENABLE);
  ALTER TABLE "SARRA"."NOURITURE" MODIFY ("TEMPS" NOT NULL ENABLE);
  ALTER TABLE "SARRA"."NOURITURE" MODIFY ("ID_MEAL" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table PRENDRE_EN_CHARGE
--------------------------------------------------------

  ALTER TABLE "SARRA"."PRENDRE_EN_CHARGE" ADD CONSTRAINT "PRENDRE_EN_CHARGE_PK" PRIMARY KEY ("ID_ANIMAL_PK1", "ID_EMPLOYE_PK2")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "SARRA"."PRENDRE_EN_CHARGE" MODIFY ("ID_EMPLOYE_PK2" NOT NULL ENABLE);
  ALTER TABLE "SARRA"."PRENDRE_EN_CHARGE" MODIFY ("ID_ANIMAL_PK1" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table PRODUITS
--------------------------------------------------------

  ALTER TABLE "SARRA"."PRODUITS" ADD CONSTRAINT "PRODUITS_PK" PRIMARY KEY ("ID_PRODUIT")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "SARRA"."PRODUITS" MODIFY ("ID_PRODUIT" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table VISITES
--------------------------------------------------------

  ALTER TABLE "SARRA"."VISITES" ADD CONSTRAINT "VISITES_PK" PRIMARY KEY ("IDENTIFIANTTICKET")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "SARRA"."VISITES" MODIFY ("IDENTIFIANTTICKET" NOT NULL ENABLE);
--------------------------------------------------------
--  Ref Constraints for Table FOURNIR
--------------------------------------------------------

  ALTER TABLE "SARRA"."FOURNIR" ADD CONSTRAINT "FOURNIR_FK1" FOREIGN KEY ("ID_PRODUIT_PK1")
	  REFERENCES "SARRA"."ANIMAUX" ("ID_ANIMAL") ENABLE;
  ALTER TABLE "SARRA"."FOURNIR" ADD CONSTRAINT "FOURNIR_FK2" FOREIGN KEY ("ID_PRODUIT_PK1")
	  REFERENCES "SARRA"."PRODUITS" ("ID_PRODUIT") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table MAGASINS
--------------------------------------------------------

  ALTER TABLE "SARRA"."MAGASINS" ADD CONSTRAINT "MAGASINS_FK1" FOREIGN KEY ("ID_EMPLOYES_FK1")
	  REFERENCES "SARRA"."EMPLOYE" ("IDENTIFIANTE") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table NOURITURE
--------------------------------------------------------

  ALTER TABLE "SARRA"."NOURITURE" ADD CONSTRAINT "NOURITURE_FK1" FOREIGN KEY ("ANIMAL")
	  REFERENCES "SARRA"."ANIMAUX" ("ID_ANIMAL") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table PRENDRE_EN_CHARGE
--------------------------------------------------------

  ALTER TABLE "SARRA"."PRENDRE_EN_CHARGE" ADD CONSTRAINT "PRENDRE_EN_CHARGE_FK1" FOREIGN KEY ("ID_ANIMAL_PK1")
	  REFERENCES "SARRA"."ANIMAUX" ("ID_ANIMAL") ENABLE;
  ALTER TABLE "SARRA"."PRENDRE_EN_CHARGE" ADD CONSTRAINT "PRENDRE_EN_CHARGE_FK2" FOREIGN KEY ("ID_EMPLOYE_PK2")
	  REFERENCES "SARRA"."EMPLOYE" ("IDENTIFIANTE") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table VISITES
--------------------------------------------------------

  ALTER TABLE "SARRA"."VISITES" ADD CONSTRAINT "VISITES_FK1" FOREIGN KEY ("ID_ANIMAL_FK1")
	  REFERENCES "SARRA"."ANIMAUX" ("ID_ANIMAL") ENABLE;
