--------------------------------------------------------
--  Fichier créé - jeudi-décembre-02-2021   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table ANIMAUX
--------------------------------------------------------

  CREATE TABLE "SARRA"."ANIMAUX" 
   (	"ID_ANIMAL" NUMBER, 
	"LIBELLE" VARCHAR2(256 BYTE), 
	"NUMERO_CAGE" NUMBER, 
	"NOURRITURE" VARCHAR2(256 BYTE), 
	"AGE" NUMBER, 
	"RECLAMATION" VARCHAR2(256 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table COMPTES
--------------------------------------------------------

  CREATE TABLE "SARRA"."COMPTES" 
   (	"IDENTIFIANT" VARCHAR2(20 BYTE), 
	"MDP" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table EMPLOYES
--------------------------------------------------------

  CREATE TABLE "SARRA"."EMPLOYES" 
   (	"ID_EMPLOYE" VARCHAR2(20 BYTE), 
	"NOM" VARCHAR2(20 BYTE), 
	"PRENOM" VARCHAR2(20 BYTE), 
	"SALAIRE" FLOAT(126), 
	"RECLAMATION" VARCHAR2(20 BYTE), 
	"ID_EMPLOYE_FK1" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table FOURNIR
--------------------------------------------------------

  CREATE TABLE "SARRA"."FOURNIR" 
   (	"ID_PRODUIT_PK1" NUMBER, 
	"ID_ANIMAL_PK2" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table MAGASINS
--------------------------------------------------------

  CREATE TABLE "SARRA"."MAGASINS" 
   (	"ID_MAGASIN" VARCHAR2(20 BYTE), 
	"PRIX_LOCATION" FLOAT(126), 
	"ETAT" NUMBER, 
	"ID_LOCATAIRE" VARCHAR2(20 BYTE), 
	"LIBELLE" VARCHAR2(20 BYTE), 
	"ID_EMPLOYES_FK1" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table PRENDRE_EN_CHARGE
--------------------------------------------------------

  CREATE TABLE "SARRA"."PRENDRE_EN_CHARGE" 
   (	"ID_ANIMAL_PK1" NUMBER, 
	"ID_EMPLOYE_PK2" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table PRODUITS
--------------------------------------------------------

  CREATE TABLE "SARRA"."PRODUITS" 
   (	"ID_PRODUIT" NUMBER, 
	"NOM_PRODUIT" VARCHAR2(20 BYTE), 
	"LIBELLE_PRODUIT" VARCHAR2(20 BYTE), 
	"NBRE_EXEMPLAIRE" NUMBER, 
	"ID_FOURNISSEUR" NUMBER, 
	"PRIX" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table VISITES
--------------------------------------------------------

  CREATE TABLE "SARRA"."VISITES" 
   (	"IDENTIFIANTTICKET" VARCHAR2(20 BYTE), 
	"PRIXTICKET" NUMBER, 
	"IDENTIFIANTVISITEUR" VARCHAR2(20 BYTE), 
	"NOMBREVISITES" NUMBER, 
	"DATEVISITE" VARCHAR2(30 BYTE), 
	"ABONNEMENT" VARCHAR2(20 BYTE), 
	"ID_ANIMAL_FK1" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
REM INSERTING into SARRA.ANIMAUX
SET DEFINE OFF;
Insert into SARRA.ANIMAUX (ID_ANIMAL,LIBELLE,NUMERO_CAGE,NOURRITURE,AGE,RECLAMATION) values ('2',null,null,null,null,null);
REM INSERTING into SARRA.COMPTES
SET DEFINE OFF;
Insert into SARRA.COMPTES (IDENTIFIANT,MDP) values ('admin','admin');
Insert into SARRA.COMPTES (IDENTIFIANT,MDP) values ('sarra','sarra');
REM INSERTING into SARRA.EMPLOYES
SET DEFINE OFF;
REM INSERTING into SARRA.FOURNIR
SET DEFINE OFF;
REM INSERTING into SARRA.MAGASINS
SET DEFINE OFF;
REM INSERTING into SARRA.PRENDRE_EN_CHARGE
SET DEFINE OFF;
REM INSERTING into SARRA.PRODUITS
SET DEFINE OFF;
Insert into SARRA.PRODUITS (ID_PRODUIT,NOM_PRODUIT,LIBELLE_PRODUIT,NBRE_EXEMPLAIRE,ID_FOURNISSEUR,PRIX) values ('54','omo','Alimentaires','5','5','4');
Insert into SARRA.PRODUITS (ID_PRODUIT,NOM_PRODUIT,LIBELLE_PRODUIT,NBRE_EXEMPLAIRE,ID_FOURNISSEUR,PRIX) values ('70','gants','Alimentaires','3','148','15');
REM INSERTING into SARRA.VISITES
SET DEFINE OFF;
Insert into SARRA.VISITES (IDENTIFIANTTICKET,PRIXTICKET,IDENTIFIANTVISITEUR,NOMBREVISITES,DATEVISITE,ABONNEMENT,ID_ANIMAL_FK1) values ('sarra','7','52','0','ven. nov. 12 2021','Oui',null);
Insert into SARRA.VISITES (IDENTIFIANTTICKET,PRIXTICKET,IDENTIFIANTVISITEUR,NOMBREVISITES,DATEVISITE,ABONNEMENT,ID_ANIMAL_FK1) values ('klp','2','1','0','dim. nov. 14 2021','Oui',null);
Insert into SARRA.VISITES (IDENTIFIANTTICKET,PRIXTICKET,IDENTIFIANTVISITEUR,NOMBREVISITES,DATEVISITE,ABONNEMENT,ID_ANIMAL_FK1) values ('testh','20','17','0','mar. nov. 9 2021','Oui',null);
Insert into SARRA.VISITES (IDENTIFIANTTICKET,PRIXTICKET,IDENTIFIANTVISITEUR,NOMBREVISITES,DATEVISITE,ABONNEMENT,ID_ANIMAL_FK1) values ('mlo','2','125','0','dim. nov. 14 2021','Oui',null);
Insert into SARRA.VISITES (IDENTIFIANTTICKET,PRIXTICKET,IDENTIFIANTVISITEUR,NOMBREVISITES,DATEVISITE,ABONNEMENT,ID_ANIMAL_FK1) values ('test','20','5','0','lun. nov. 15 2021','Oui',null);
Insert into SARRA.VISITES (IDENTIFIANTTICKET,PRIXTICKET,IDENTIFIANTVISITEUR,NOMBREVISITES,DATEVISITE,ABONNEMENT,ID_ANIMAL_FK1) values ('ttest','7','2','0','mar. nov. 16 2021','Oui',null);
Insert into SARRA.VISITES (IDENTIFIANTTICKET,PRIXTICKET,IDENTIFIANTVISITEUR,NOMBREVISITES,DATEVISITE,ABONNEMENT,ID_ANIMAL_FK1) values ('abbc','8','12','2','lun. nov. 8 2021','Oui',null);
Insert into SARRA.VISITES (IDENTIFIANTTICKET,PRIXTICKET,IDENTIFIANTVISITEUR,NOMBREVISITES,DATEVISITE,ABONNEMENT,ID_ANIMAL_FK1) values ('sml','25','148','0','mar. nov. 9 2021','Non',null);
Insert into SARRA.VISITES (IDENTIFIANTTICKET,PRIXTICKET,IDENTIFIANTVISITEUR,NOMBREVISITES,DATEVISITE,ABONNEMENT,ID_ANIMAL_FK1) values ('smll','25','148','0','mar. nov. 9 2021','Non',null);
Insert into SARRA.VISITES (IDENTIFIANTTICKET,PRIXTICKET,IDENTIFIANTVISITEUR,NOMBREVISITES,DATEVISITE,ABONNEMENT,ID_ANIMAL_FK1) values ('ll','8','7','0','lun. nov. 8 2021','Oui',null);
Insert into SARRA.VISITES (IDENTIFIANTTICKET,PRIXTICKET,IDENTIFIANTVISITEUR,NOMBREVISITES,DATEVISITE,ABONNEMENT,ID_ANIMAL_FK1) values ('kjj','3','76','0','mar. nov. 30 2021','Oui',null);
Insert into SARRA.VISITES (IDENTIFIANTTICKET,PRIXTICKET,IDENTIFIANTVISITEUR,NOMBREVISITES,DATEVISITE,ABONNEMENT,ID_ANIMAL_FK1) values ('kl','5','4','0','lun. nov. 8 2021','Oui',null);
Insert into SARRA.VISITES (IDENTIFIANTTICKET,PRIXTICKET,IDENTIFIANTVISITEUR,NOMBREVISITES,DATEVISITE,ABONNEMENT,ID_ANIMAL_FK1) values ('ok','8','3','0','lun. nov. 8 2021','Oui',null);
Insert into SARRA.VISITES (IDENTIFIANTTICKET,PRIXTICKET,IDENTIFIANTVISITEUR,NOMBREVISITES,DATEVISITE,ABONNEMENT,ID_ANIMAL_FK1) values ('m','7','5','0','lun. nov. 8 2021','Oui',null);
Insert into SARRA.VISITES (IDENTIFIANTTICKET,PRIXTICKET,IDENTIFIANTVISITEUR,NOMBREVISITES,DATEVISITE,ABONNEMENT,ID_ANIMAL_FK1) values ('kh','65','2','0','lun. nov. 8 2021','Oui',null);
Insert into SARRA.VISITES (IDENTIFIANTTICKET,PRIXTICKET,IDENTIFIANTVISITEUR,NOMBREVISITES,DATEVISITE,ABONNEMENT,ID_ANIMAL_FK1) values ('smllk','14','67','4','mar. nov. 9 2021','Non',null);
Insert into SARRA.VISITES (IDENTIFIANTTICKET,PRIXTICKET,IDENTIFIANTVISITEUR,NOMBREVISITES,DATEVISITE,ABONNEMENT,ID_ANIMAL_FK1) values ('kdj','2','123','0','mar. nov. 9 2021','Oui',null);
Insert into SARRA.VISITES (IDENTIFIANTTICKET,PRIXTICKET,IDENTIFIANTVISITEUR,NOMBREVISITES,DATEVISITE,ABONNEMENT,ID_ANIMAL_FK1) values ('mm','8','45','0','mar. nov. 9 2021','Oui',null);
Insert into SARRA.VISITES (IDENTIFIANTTICKET,PRIXTICKET,IDENTIFIANTVISITEUR,NOMBREVISITES,DATEVISITE,ABONNEMENT,ID_ANIMAL_FK1) values ('mol','14','36','0','mar. nov. 9 2021','Oui',null);
Insert into SARRA.VISITES (IDENTIFIANTTICKET,PRIXTICKET,IDENTIFIANTVISITEUR,NOMBREVISITES,DATEVISITE,ABONNEMENT,ID_ANIMAL_FK1) values ('tttest','7','2','0','mar. nov. 16 2021','Oui',null);
Insert into SARRA.VISITES (IDENTIFIANTTICKET,PRIXTICKET,IDENTIFIANTVISITEUR,NOMBREVISITES,DATEVISITE,ABONNEMENT,ID_ANIMAL_FK1) values ('dora','11','869','3','mar. nov. 16 2021','Oui',null);
Insert into SARRA.VISITES (IDENTIFIANTTICKET,PRIXTICKET,IDENTIFIANTVISITEUR,NOMBREVISITES,DATEVISITE,ABONNEMENT,ID_ANIMAL_FK1) values ('papa','5','53','0','mar. nov. 23 2021','Oui',null);
Insert into SARRA.VISITES (IDENTIFIANTTICKET,PRIXTICKET,IDENTIFIANTVISITEUR,NOMBREVISITES,DATEVISITE,ABONNEMENT,ID_ANIMAL_FK1) values ('plo','4','15','2','mer. d??c. 1 2021','Oui',null);
Insert into SARRA.VISITES (IDENTIFIANTTICKET,PRIXTICKET,IDENTIFIANTVISITEUR,NOMBREVISITES,DATEVISITE,ABONNEMENT,ID_ANIMAL_FK1) values ('mpl','8','23','9','mer. d??c. 1 2021','Non',null);
Insert into SARRA.VISITES (IDENTIFIANTTICKET,PRIXTICKET,IDENTIFIANTVISITEUR,NOMBREVISITES,DATEVISITE,ABONNEMENT,ID_ANIMAL_FK1) values ('testA','25','258','0','mer. d??c. 1 2021','Oui','2');
Insert into SARRA.VISITES (IDENTIFIANTTICKET,PRIXTICKET,IDENTIFIANTVISITEUR,NOMBREVISITES,DATEVISITE,ABONNEMENT,ID_ANIMAL_FK1) values ('amin','1','3','0','mer. d??c. 1 2021','Oui',null);
Insert into SARRA.VISITES (IDENTIFIANTTICKET,PRIXTICKET,IDENTIFIANTVISITEUR,NOMBREVISITES,DATEVISITE,ABONNEMENT,ID_ANIMAL_FK1) values ('testm','15','86','0','mer. d??c. 1 2021','Oui','2');
Insert into SARRA.VISITES (IDENTIFIANTTICKET,PRIXTICKET,IDENTIFIANTVISITEUR,NOMBREVISITES,DATEVISITE,ABONNEMENT,ID_ANIMAL_FK1) values ('pdml','1','158','0','jeu. d??c. 2 2021','Oui',null);
Insert into SARRA.VISITES (IDENTIFIANTTICKET,PRIXTICKET,IDENTIFIANTVISITEUR,NOMBREVISITES,DATEVISITE,ABONNEMENT,ID_ANIMAL_FK1) values ('pdmll','1','158','0','jeu. d??c. 2 2021','Oui','2');
--------------------------------------------------------
--  DDL for Index ANIMAUX_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "SARRA"."ANIMAUX_PK" ON "SARRA"."ANIMAUX" ("ID_ANIMAL") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index EMPLOYES_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "SARRA"."EMPLOYES_PK" ON "SARRA"."EMPLOYES" ("ID_EMPLOYE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index FOURNIR_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "SARRA"."FOURNIR_PK" ON "SARRA"."FOURNIR" ("ID_PRODUIT_PK1", "ID_ANIMAL_PK2") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index MAGASINS_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "SARRA"."MAGASINS_PK" ON "SARRA"."MAGASINS" ("ID_MAGASIN") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index PRENDRE_EN_CHARGE_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "SARRA"."PRENDRE_EN_CHARGE_PK" ON "SARRA"."PRENDRE_EN_CHARGE" ("ID_ANIMAL_PK1", "ID_EMPLOYE_PK2") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index PRODUITS_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "SARRA"."PRODUITS_PK" ON "SARRA"."PRODUITS" ("ID_PRODUIT") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index VISITES_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "SARRA"."VISITES_PK" ON "SARRA"."VISITES" ("IDENTIFIANTTICKET") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  Constraints for Table ANIMAUX
--------------------------------------------------------

  ALTER TABLE "SARRA"."ANIMAUX" ADD CONSTRAINT "ANIMAUX_PK" PRIMARY KEY ("ID_ANIMAL")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "SARRA"."ANIMAUX" MODIFY ("ID_ANIMAL" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table EMPLOYES
--------------------------------------------------------

  ALTER TABLE "SARRA"."EMPLOYES" ADD CONSTRAINT "EMPLOYES_PK" PRIMARY KEY ("ID_EMPLOYE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "SARRA"."EMPLOYES" MODIFY ("ID_EMPLOYE" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table FOURNIR
--------------------------------------------------------

  ALTER TABLE "SARRA"."FOURNIR" ADD CONSTRAINT "FOURNIR_PK" PRIMARY KEY ("ID_PRODUIT_PK1", "ID_ANIMAL_PK2")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "SARRA"."FOURNIR" MODIFY ("ID_ANIMAL_PK2" NOT NULL ENABLE);
  ALTER TABLE "SARRA"."FOURNIR" MODIFY ("ID_PRODUIT_PK1" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table MAGASINS
--------------------------------------------------------

  ALTER TABLE "SARRA"."MAGASINS" ADD CONSTRAINT "MAGASINS_PK" PRIMARY KEY ("ID_MAGASIN")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "SARRA"."MAGASINS" MODIFY ("ID_MAGASIN" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table PRENDRE_EN_CHARGE
--------------------------------------------------------

  ALTER TABLE "SARRA"."PRENDRE_EN_CHARGE" ADD CONSTRAINT "PRENDRE_EN_CHARGE_PK" PRIMARY KEY ("ID_ANIMAL_PK1", "ID_EMPLOYE_PK2")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "SARRA"."PRENDRE_EN_CHARGE" MODIFY ("ID_EMPLOYE_PK2" NOT NULL ENABLE);
  ALTER TABLE "SARRA"."PRENDRE_EN_CHARGE" MODIFY ("ID_ANIMAL_PK1" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table PRODUITS
--------------------------------------------------------

  ALTER TABLE "SARRA"."PRODUITS" ADD CONSTRAINT "PRODUITS_PK" PRIMARY KEY ("ID_PRODUIT")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "SARRA"."PRODUITS" MODIFY ("ID_PRODUIT" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table VISITES
--------------------------------------------------------

  ALTER TABLE "SARRA"."VISITES" ADD CONSTRAINT "VISITES_PK" PRIMARY KEY ("IDENTIFIANTTICKET")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "SARRA"."VISITES" MODIFY ("IDENTIFIANTTICKET" NOT NULL ENABLE);
--------------------------------------------------------
--  Ref Constraints for Table EMPLOYES
--------------------------------------------------------

  ALTER TABLE "SARRA"."EMPLOYES" ADD CONSTRAINT "EMPLOYES_FK1" FOREIGN KEY ("ID_EMPLOYE_FK1")
	  REFERENCES "SARRA"."EMPLOYES" ("ID_EMPLOYE") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table FOURNIR
--------------------------------------------------------

  ALTER TABLE "SARRA"."FOURNIR" ADD CONSTRAINT "FOURNIR_FK1" FOREIGN KEY ("ID_PRODUIT_PK1")
	  REFERENCES "SARRA"."ANIMAUX" ("ID_ANIMAL") ENABLE;
  ALTER TABLE "SARRA"."FOURNIR" ADD CONSTRAINT "FOURNIR_FK2" FOREIGN KEY ("ID_PRODUIT_PK1")
	  REFERENCES "SARRA"."PRODUITS" ("ID_PRODUIT") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table MAGASINS
--------------------------------------------------------

  ALTER TABLE "SARRA"."MAGASINS" ADD CONSTRAINT "MAGASINS_FK1" FOREIGN KEY ("ID_EMPLOYES_FK1")
	  REFERENCES "SARRA"."EMPLOYES" ("ID_EMPLOYE") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table PRENDRE_EN_CHARGE
--------------------------------------------------------

  ALTER TABLE "SARRA"."PRENDRE_EN_CHARGE" ADD CONSTRAINT "PRENDRE_EN_CHARGE_FK1" FOREIGN KEY ("ID_ANIMAL_PK1")
	  REFERENCES "SARRA"."ANIMAUX" ("ID_ANIMAL") ENABLE;
  ALTER TABLE "SARRA"."PRENDRE_EN_CHARGE" ADD CONSTRAINT "PRENDRE_EN_CHARGE_FK2" FOREIGN KEY ("ID_EMPLOYE_PK2")
	  REFERENCES "SARRA"."EMPLOYES" ("ID_EMPLOYE") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table VISITES
--------------------------------------------------------

  ALTER TABLE "SARRA"."VISITES" ADD CONSTRAINT "VISITES_FK1" FOREIGN KEY ("ID_ANIMAL_FK1")
	  REFERENCES "SARRA"."ANIMAUX" ("ID_ANIMAL") ENABLE;
